---
stages:
  - build
  - publish

variables:
  BASE_IMAGE_TAG: 3-alpine
  VERSION: 1.1.3

build-job:
  stage: build
  script:
    - docker build --build-arg BASE_IMAGE_TAG=$BASE_IMAGE_TAG --build-arg VERSION=$VERSION -t $CI_REGISTRY_IMAGE:$VERSION -t $CI_REGISTRY_IMAGE:latest .

publish-job:
  stage: publish
  script:
    - echo "$CI_JOB_TOKEN" | docker login --password-stdin -u $CI_REGISTRY_USER $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
...
